[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
from = "/content/images/*"
status = 200
to = "https://ghost.jonnev.dev/content/images/:splat"
